### PR TITLE
meter doc

### PR DESCRIPTION
**Pull request by kanesamoa**
- [ ] Type: Sidechain

- [ ] Transaction cost: $0.01

- [ ] Finality: 7s

- [ ] Consensus: Proof of Value (PoV) 

- [ ] Capital Efficiency: No

- [ ] Max TPS: 1500 TPS

- [ ] Additional info:

https://docs.meter.io/introduction-to-meter

https://www.meter.io/meter-roadmap-update-oct2020/

- [ ] Social media and community links:

[Website](https://www.meter.io/)

[Twitter](https://twitter.com/Meter_IO)

[Github](https://github.com/meterio)

[Youtube](https://www.youtube.com/channel/UCgQVD2Ab-i3IKUhjs6-Z76w)

[Medium](https://medium.com/meter-io)

[Discord](https://discord.com/invite/XZgZsCn)

[Telegram](https://t.me/Meter_IO)

[Instagram](https://www.instagram.com/accounts/meter.io/)

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Review by chair28980 — APPROVED** [review]

**Comment by chair28980** [comment]
@YalorMewn this fine submitter: https://github.com/kanesamoa is good for payment for this PR.

**Comment by YalorMewn** [comment]
Sorry for the delay on payment here guys, it's 200 + gas rn 😑

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/122

**Comment by kanesamoa** [comment]
@chair28980 @YalorMewn Hey, I asked vinh (vnh) to receive my reward, I've been waiting for it since 1/2/21.

**Comment by kanesamoa** [comment]
@YalorMewn My xdai address is 0xC42Ec4d9Cd53621D6925d67970dF07878928C007

**Comment by kanesamoa** [comment]
https://gitcoin.co/issue/raid-guild/indexed/81/100024657 #81 
My PR #92 has been accepted. You can pay rewards from gitcoin L2 bounty (v2) to the xdai address I sent above. Thank you.

**Comment by ManyRios** [comment]
more than 15 days of delay... too bad 😞

**Pull request closed without merging**
