### PR TITLE
update matter labs doc

### PR DESCRIPTION
**Pull request by vinhbhn**
- [x] Type: ZKSNARK

- [x] Transaction cost: $0.001 (off-chain), 1,9k gas (on-chain)

- [x] Finality: [10 minutes.](https://zksync.io/faq/tech.html#transaction-finality)

- [x] Consensus: [Validity proofs](https://zksync.io/faq/security.html#validity-proofs)

- [x] Capital Efficient: [Yes (withdrawals to L1 in under 15 min).](https://zksync.io/faq/intro.html#zksync-features)

- [x] Max TPS: 2000 TPS (currently 300+ TPS)

- [x] Additional info:
- security: secure as L1

- generality: support smart contracts (written in Zinc), and existing Solidity code can easily be translated into Zinc (but Zinc is currently non-Turing-complete as Solidity. Its means: recursion and unbounded loops are prohibited)

- composability: support composability (All contracts inside zkSync L2 network will be able to call each other atomically in exactly the same way as on Ethereum mainnet).

- permissionless innovation: The token is currently added manually, but in the future it is possible to deploy the token.(https://zksync.io/faq/tokens.html#supported-tokens)

Links: 
[Website](https://matter-labs.io/)

[Twitter](https://twitter.com/the_matter_labs)

[Github](https://github.com/matter-labs)

[Telegram](https://t.me/matterlabs)

[Medium](https://medium.com/matter-labs)

[Gitter](https://gitter.im/matter-labs/community)

Source: 
https://zksync.io/faq/intro.html

https://medium.com/matter-labs/curve-zksync-l2-ethereums-first-user-defined-zk-rollup-smart-contract-5a72c496b350

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Comment by vinhbhn** [comment]
Hi @bighappytrees, I have updated the file, you can review it.

**Review by chair28980 — APPROVED** [review]
LGTM!

**Comment by chair28980** [comment]
@vinhbhn ty!

**Review by chair28980 — APPROVED** [review]
LGTM!

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/64

**Pull request closed without merging**
