### PR TITLE
Filled in info for loopring

### PR DESCRIPTION
**Pull request by javipus**
- [x] Type: Chain-agnostic, L2 protcol based on zkRollups

- [x] Transaction cost: 450 gas (~$0.0002 on Ethereum as of 2021/01/14)

- [x] Finality: Apparently immediate (off-chain), later verified on-chain

- [x] Consensus: zkRollup

- [x] Capital Efficient: More capital efficient than main alternatives as long as off-chain cloud compute is cheaper than on-chain transactions (see table 1 [here](https://vitalik.ca/general/2021/01/05/rollup.html))

- [x] Max TPS: 2,025 with OCDA; 16,400 without

- [x] Additional info:
1. [Protocol overview](https://loopring.org/#/protocol)
2. [Loopring 3 Design Doc](https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/DESIGN.md)
3. [Discord](https://discord.gg/KkYccYp)
4. [Twitter](https://twitter.com/loopringorg)
5. [Reddit](https://reddit.com/r/loopringorg)
6. [Telegram](https://t.me/loopring_en)

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Review by chair28980 — CHANGES_REQUESTED** [review]
@javipus thank you for the submission! Can you hunt down any available links to socials/communites? Thank you!

**Comment by javipus** [comment]
@bighappytrees I've added social links as requested.

**Review by chair28980 — APPROVED** [review]
LGTM

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/65

**Pull request closed without merging**
