### PR TITLE
Arbitrum Research

### PR DESCRIPTION
**Pull request by AaronTheBruce**
- [x] Type:

AVM

- [x] Transaction cost:

Uses ArbGas which is a calculated to determine gas, so these are estimates

30 gwei
transaction fee: 0.0022 ETH

- [x] Finality

See 5.2 Iterated Hashing for [usenixsecurity18](https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-kalodner.pdf)

TLDR:
using a 2013 Apple MacBook Pro, 2.7GHz Intel Core i7

1.7 million hashes per second

 "Running the VM continuously we were able to
advance the VM by 970,000 hashes per second."

- [x] Consensus:

Proof of Stake and Plasma

#### "consensus-agnostic"
- Arbitrum uses and refers to consensus as 'verifiers' that assumes the existence of a consensus mechanism, including a...
  - single centralized publisher,
  - a quorum-based consensus system,
  - or Nakamoto consensus as used in Bitcoin

- [x] Capital Efficient:

Arbitrum’s VM architecture makes dispute resolution very efficient.

"Even if parties behave counter to their incentives, Arbitrum verifiers can efficiently adjudicate disputes about contract behavior without needing to examine the execution of more than one instruction by the contract."

- [x] Max TPS:

Up To 4,500 transactions per second

- [x] Additional info:

- Compatible with Ethereum, Solidity Smart Contract code is comipled with Arbitrum
- Only verifies digital signatures instead of every part of the contract for the VM

[usenix.org](https://www.usenix.org/conference/usenixsecurity18/presentation/kalodner)

[Forbes article](https://www.forbes.com/sites/forbes-personal-shopper/2021/01/13/the-best-planners-for-2021/?sh=6b46e6905255)

[Official Site](https://offchainlabs.com/)

[usenixsecurity18](https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-kalodner.pdf)

[Offchainlabs dev docs](https://developer.offchainlabs.com/docs/rollup_basics)

[Offchainlabs white paper](https://offchainlabs.com/Arbitrum_Rollup_Whitepaper.pdf)

[How Arbitrum Channels Work](https://medium.com/offchainlabs/how-arbitrum-works-6eaccb47cd86#:~:text=Arbitrum%20deters%20misbehavior%20by%20requiring,it%20will%20forfeit%20its%20stake.)

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Review by chair28980 — APPROVED** [review]

**Comment by chair28980** [comment]
@AaronTheBruce goldstar!

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/55

**Comment by chair28980** [comment]
@YalorMewn this fine submitter should be paid 👍

**Comment by chair28980** [comment]
@AaronTheBruce would you like to do some further work with this project related to more in depth research and written content that is outside the gitcoin grant? Please let me know if you are interested: vrycmfy@protonmail.com thank you!

**Comment by YalorMewn** [comment]
PAID: Sorry for the delay @AaronTheBruce 🙏

**Pull request closed without merging**
