### PR TITLE
Raiden

### PR DESCRIPTION
**Pull request by ManyRios**
- [ ] Type: 
 State Channel (off chain)
- [ ] Transaction cost:
Is denominated in the token that is transferred in the channel.

- [ ] Finality
Instant

- [ ] Consensus:
Proof of stake

- [ ] Capital Efficient:
YES

- [ ] Max TPS:
100k txn/s.

- [ ] Additional info:

- https://medium.com/raiden-network/raiddit-scaling-reddit-community-points-with-raiden-9fe60c14ae47

- https://developer.raiden.network/

- https://twitter.com/raiden_network

- https://medium.com/@raiden_network

- https://www.youtube.com/channel/UCoUP_hnjUddEvbxmtNCcApg

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Review by chair28980 — APPROVED** [review]
LGTM

**Comment by chair28980** [comment]
@ManyRios nice thank you!

**Comment by ManyRios** [comment]
> @ManyRios nice thank you!

Thanks to you

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/70

**Comment by chair28980** [comment]
@ManyRios My apologies!!!!!

In the wave of submissions I overlooked the enormous commit you have here.

@YalorMewn This fine person should certainly be paid.

@ManyRios I can see now how much data you collected! Would you like to work with me on a few specific tasks related to this projects outside of the scope of the gitcoin tasks? Let me know! My email is vrycmfy@protonmail.com

**Comment by chair28980** [comment]
@ManyRios There is some more in depth research we are finding is required. I'm sure we can work out something comfy with @YalorMewn. Again if you're interested let me know at that email, thank you!

**Comment by chair28980** [comment]
This is in reference to conversation in https://github.com/raid-guild/indexed/pull/63

**Comment by ManyRios** [comment]
I leave you a email :)

**Comment by YalorMewn** [comment]
Great work @ManyRios I just paid you out, let's T up some more of these bounties for you !

**Pull request closed without merging**
