### PR TITLE
update celer doc

### PR DESCRIPTION
**Pull request by vinhbhn**
- [x] Type: State Channel and Hybrid Rollup

- [x] Transaction cost: 0 (off-chain)

- [x] Finality: Instant

- [x] Consensus: DPoS-Rollup

- [x] Capital Efficiency: No

- [x] Max TPS: 4k TPS

- [x] Additional info:

https://medium.com/celer-network/adding-hybrid-pos-rollup-sidechain-to-celers-coherent-layer-2-platform-d1d3067fe593

https://www.celer.network/docs/celercore/channel/overview.html

- [x] Social media and community links:

[Website](https://www.celer.network/)

[Twitter](https://twitter.com/CelerNetwork)

[Medium](https://medium.com/celer-network)

[Github](https://github.com/celer-network)

[Discord](https://discord.com/invite/Trhab5w)

[Telegram](https://t.me/celernetwork)

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Comment by chair28980** [comment]
@chair28980 check if correct form submission exists

**Comment by chair28980** [comment]
https://docs.google.com/forms/d/1TRIjPaA5yGj7q7qilHlSLU5OQsjRFfJtkD7eULcXafo/edit#response=ACYDBNhp9kM8nI85-H3N3ZEySxZnffa2f44iK6xdfu1MOC1aIRLoI6Z-G6fgBs5f9GDO3_M

Form submission good.

@YalorMewn this fine submitter: https://github.com/vinhbhn is g2g for payment for this PR.

**Review by chair28980 — APPROVED** [review]

**Comment by chair28980** [comment]
Merged in https://github.com/raid-guild/indexed/pull/121

**Comment by chair28980** [comment]
@vinhbhn Hallo!

Please email vrycmfy@protonmail.com if you would like more work like this, thank you!

**Comment by YalorMewn** [comment]
Sorry for the delay on payment here guys, it's 200 + gas rn 😑

**Comment by vinhbhn** [comment]
@YalorMewn You can use ftx exchange, free withdraw, exchange will be charged on the network.

**Comment by vinhbhn** [comment]
@YalorMewn You can use ftx exchange, free withdraw, network fee will be borne by the exchange.

**Pull request closed without merging**
