### PR TITLE
Data entry Solana

### PR DESCRIPTION
**Pull request by molecula451**
- [x] Type:

- [x] Transaction cost:

- [x] Finality

- [x] Consensus:

- [x] Capital Efficient:

- [x] Max TPS:

- [x] Additional info:

## Reviewer checklist

- [x] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [x] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Review by chair28980 — CHANGES_REQUESTED** [review]
@molecula451 thank you for the submission! Can you hunt down a few links to the projects socials/communities/docs etc?

**Comment by molecula451** [comment]
@bighappytrees added few resources link + an invitation to discord channel

**Review by chair28980 — APPROVED** [review]
LGTM!

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/issues/50

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/61

**Pull request closed without merging**
