### PR TITLE
Raiden Network

### PR DESCRIPTION
**Pull request by ManyRios**
- [ ] Type: 
 State Channel (off chain)
- [ ] Transaction cost:
Is denominated in the token that is transferred in the channel.

- [ ] Finality
Instant

- [ ] Consensus:
Proof of stake

- [ ] Capital Efficient:
YES

- [ ] Max TPS:
100k txn/s.

- [ ] Additional info:

- https://medium.com/raiden-network/raiddit-scaling-reddit-community-points-with-raiden-9fe60c14ae47

- https://developer.raiden.network/

- https://twitter.com/raiden_network

- https://medium.com/@raiden_network

- https://www.youtube.com/channel/UCoUP_hnjUddEvbxmtNCcApg

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Comment by ManyRios** [comment]
Any changes  to do here sir?

**Comment by chair28980** [comment]
@ManyRios Hello! Thank your for your contribution, let me review and let you know.

**Comment by chair28980** [comment]
@ManyRios Thank you for your submission. We will be updating the styles and table layout shortly, as well as continually updating the docs. It appears you attempted to updated the Raiden docs but I don't see the corresponding files. Can you try opening a new pull request and submitting the information again? Thank you!

**Comment by ManyRios** [comment]
This PR wasn't paid but you still use the info submitted?  
image

**Comment by chair28980** [comment]
@ManyRios im looking into this now, i will follow up shortly. Was this the only pr you submitted?

**Comment by ManyRios** [comment]
https://github.com/raid-guild/indexed/pull/63 where the changes has been made

**Comment by ManyRios** [comment]
> #63 where the changes has been made

yes is the only PR

**Comment by chair28980** [comment]
Comments left in #63 for Many, dont wanna over ping.

**Pull request closed without merging**
