### PR TITLE
Create kchannels-doc.md

### PR DESCRIPTION
**Pull request by Timidan**
The following items should be included as headers in the markdown document (##).

This is the MIN information required, and you are encouraged to include as much information as you can track down.

Please include links to

- [x] Type:

- [x] Transaction cost:

- [x] Finality

- [x] Consensus:

- [x] Capital Efficiency:

- [x] Max TPS:

- [x] Additional info:

- [x] Social media and community links:

## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Comment by Timidan** [comment]
you mean someone already submitted info about kchannels?

**Comment by chair28980** [comment]
@YalorMewn this is good to pay for https://github.com/Timidan

**Comment by chair28980** [comment]
@Timidan please email vrycmfy@protonmail.com if you'd like more work along these same lines for this project, thank you!

**Comment by chair28980** [comment]
@Timidan Sorry i didn't see your comment above, yes someone from Kchannels team submitted some slightly different info but no sweat you will be paid for the PR, also please see comment above, thank you!

**Pull request closed without merging**
