### PR TITLE
Update aztec-doc.md

### PR DESCRIPTION
**Pull request by Timidan**
- [x] Type:
 zK-Snark

- [x] Transaction cost:
 $0.000001(in Testnet)

- [x] Finality
 instant

- [x] Consensus:
 Roll-up proofs

- [x] Capital Efficient:
 YES
https://medium.com/aztec-protocol/aztec-zkrollup-layer-2-privacy-1978e90ee3b6
- [x] Max TPS:
  300 txn/s
- [x] Additional info:

http://developers.aztec.network/
## Reviewer checklist

- [ ] The code follows the guidelines outlined in the Contribution Guide

## Developer checklist

- [ ] Please provide proof of participation within the service/project you are updating
- [ ] The code follows the guidelines outlined in the Contribution Guide

### CODE REVIEW

**Review by chair28980 — CHANGES_REQUESTED** [review]
@Timidan thank you for the submission! Can you hunt down a few more links to relevant docs/socials/communities that might be out there for this service?

**Comment by Timidan** [comment]
Sure

**Comment by Timidan** [comment]
Sure

**Comment by Timidan** [comment]
Done!!

**Review by chair28980 — APPROVED** [review]
LGTM!

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/62

**Pull request closed without merging**
